[tool.poetry]
name = "blobopera"
version = "0.1.0"
description = "Unofficial Google Arts & Culture Blob Opera toolkit"
authors = ["Helio Machado <0x2b3bfa0@googlemail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
music21 = "^6.3.0"
requests = "^2.25.1"
matplotlib = "^3.3.3"
numpy = "^1.19.4"
proto-plus = "^1.13.0"
typer = {extras = ["all"], version = "^0.3.2"}
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
grpcio-tools = "^1.34.0"
pytest = "^5.2"
typer-cli = "^0.0.11"
isort = "^5.7.0"
autoflake = "^1.4"
coverage = {extras = ["toml"], version = "^5.3.1"}
flake8 = "^3.8.4"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^20.11.1"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.3.1"
flake8-eradicate = "^1.0.0"
flake8-isort = "^4.0.0"
flake8-pytest-style = "^1.3.0"
flakehell = "^0.7.1"
pep8-naming = "^0.11.1"
responses = "^0.12.1"
poethepoet = "^0.9.0"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
blobopera = "blobopera.command:application"

[tool.coverage.run]
omit = [".*", "*/site-packages/*"]

[tool.coverage.report]
fail_under = 80

[tool.flakehell]
format = "grouped"
max_line_length = 79
show_source = true
per_file_ignores=[""]

[tool.flakehell.plugins]
pyflakes = ["+*"]
flake8-bandit = ["+*"]
"flake8-*" = ["+*", "-SC*"]

[tool.flakehell.exceptions."tests/*.py"]
flake8-bandit = ["-S101"]
"flake8-*" = ["-A001"]
pyflakes = ["-F811", "-F401"]

[tool.flakehell.exceptions."blobopera/language.py"]
flake8-bandit = ["-S311"]

[tool.flakehell.exceptions."blobopera/command/*.py"]
"flake8-*" = ["-A001", "-A002", "-B008"]

[tool.poe.tasks]

isort = "isort --profile black -m 3 ."
autoflake = "autoflake --recursive --in-place --remove-unused-variables ."
black = "black --line-length=79 ."
style = ["isort", "autoflake", "black"]
lint = "flakehell lint"
test = "pytest"
coverage = {"shell" = "coverage run -m pytest; coverage report -m"}
document = "typer blobopera.command utils docs --output documentation/command/README.md --name blobopera"
all = ["style", "lint", "test", "coverage", "document"]
