name: style

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run
      run: |
        poetry run poe style
        git config --global user.name '0x2b3bfa0'
        git config --global user.email '0x2b3bfa0@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout $GITHUB_HEAD_REF
        git commit --all --message "fixup: Format code with Black" || true
        git push || true
